// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "apply" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ApplySection(): React.JSX.Element {
  return (
    <div id="apply" data-section="apply">
        <SectionErrorBoundary name="apply">
              <ContactCta
          tag="Qualification"
          text="See If You Qualify. To maintain service quality, we only accept a limited number of businesses each quarter. Answer a few questions to determine if we're a fit."
          primaryButton={{
            text: "Apply For Partnership",
            href: "#",
          }}
          secondaryButton={{
            text: "Contact Support",
            href: "#",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
