/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Star } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import { cls } from "@/lib/utils";

const testimonials = [
  {
    name: "Elena P.",
    role: "Director, AgencyX",
    quote: "Finally, a partner that acts like an extension of our internal team.",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/office-chair-still-life_23-2151149095.jpg"
  },
  {
    name: "Sarah J.",
    role: "CEO, TechCorp",
    quote: "GenGarden completely shifted our pipeline from scattered to predictable.",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/room-with-wooden-desktop-comfortable-chair_116348-96.jpg"
  },
  {
    name: "Mark D.",
    role: "Founder, LeadCo",
    quote: "Unmatched qualification quality. My sales team is finally focusing on closing.",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/modern-minimalist-office_23-2151780690.jpg"
  },
  {
    name: "Tom V.",
    role: "VP Sales, Growthly",
    quote: "Consistency, clarity, and genuine results every single quarter.",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/luxury-design-modern-wooden-table-decor-generated-by-ai_188544-27803.jpg"
  },
  {
    name: "Peter H.",
    role: "Founder, GenGarden",
    quote: "Growth comes from consistently putting the right offer in front of the right people. We focus on conversations, not noise.",
    rating: 5,
    imageSrc: "http://img.b2bpic.net/free-photo/chair-front-businesswoman-sitting-caf_23-2147876643.jpg"
  }
];

type Testimonial = {
  name: string;
  role: string;
  quote: string;
  rating: number;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const FounderInline = () => {
  return (
    <section aria-label="Testimonials section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Founder Principle"}</p>
          </div>

          <TextAnimation
            text={"A Note on Growth"}
            variant="slide-up"
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Most businesses don't need more marketing. They need more conversations with qualified buyers."}
            variant="slide-up"
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="fade">
          <GridOrCarousel>
            {testimonials.map((testimonial) => (
              <div key={testimonial.name} className="flex flex-col justify-between gap-4 xl:gap-5 2xl:gap-6 h-full p-6 xl:p-7 2xl:p-8 rounded card">
                <div className="flex flex-col items-start gap-4 xl:gap-5 2xl:gap-6">
                  <div className="flex gap-1.5">
                    {Array.from({ length: 5 }).map((_, index) => (
                      <Star
                        key={index}
                        className={cls("size-5 text-accent", index < testimonial.rating ? "fill-accent" : "fill-transparent")}
                        strokeWidth={1.5}
                      />
                    ))}
                  </div>

                  <p className="text-lg leading-snug">{testimonial.quote}</p>
                </div>

                <div className="flex items-center gap-3">
                  <ImageOrVideo
                    imageSrc={testimonial.imageSrc}
                    videoSrc={testimonial.videoSrc}
                    className="size-10 md:size-11 2xl:size-12 rounded-full object-cover"
                  />
                  <div className="flex flex-col min-w-0">
                    <span className="text-base text-foreground font-semibold leading-snug truncate">{testimonial.name}</span>
                    <span className="text-base text-foreground/75 leading-snug truncate">{testimonial.role}</span>
                  </div>
                </div>
              </div>
            ))}
          </GridOrCarousel>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function FounderSection() {
  return (
    <div data-webild-section="founder" id="founder">
      <FounderInline />
    </div>
  );
}
