// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "founder" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FounderSection(): React.JSX.Element {
  return (
    <div id="founder" data-section="founder">
        <SectionErrorBoundary name="founder">
              <TestimonialRatingCards
          tag="Founder Principle"
          title="A Note on Growth"
          description="Most businesses don't need more marketing. They need more conversations with qualified buyers."
          testimonials={[
            {
              name: "Alex River",
              role: "Founder, GenGarden",
              quote: "Growth comes from consistently putting the right offer in front of the right people. We focus on conversations, not noise.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/chair-front-businesswoman-sitting-caf_23-2147876643.jpg",
            },
            {
              name: "Sarah J.",
              role: "CEO, TechCorp",
              quote: "GenGarden completely shifted our pipeline from scattered to predictable.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/room-with-wooden-desktop-comfortable-chair_116348-96.jpg",
            },
            {
              name: "Mark D.",
              role: "Founder, LeadCo",
              quote: "Unmatched qualification quality. My sales team is finally focusing on closing.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/modern-minimalist-office_23-2151780690.jpg",
            },
            {
              name: "Elena P.",
              role: "Director, AgencyX",
              quote: "Finally, a partner that acts like an extension of our internal team.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/office-chair-still-life_23-2151149095.jpg",
            },
            {
              name: "Tom V.",
              role: "VP Sales, Growthly",
              quote: "Consistency, clarity, and genuine results every single quarter.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/luxury-design-modern-wooden-table-decor-generated-by-ai_188544-27803.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
