// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplit from '@/components/sections/hero/HeroSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplit
        tag="Selective Growth Partner"
        title="Growth Shouldn't Be Random."
        description="We build predictable client acquisition systems that connect businesses with qualified buyers ready to start conversations."
        primaryButton={{"text":"See If You Qualify","href":"#apply"}}
        secondaryButton={{
            text: "View Our Process",
            href: "#process",
          }}
        imageSrc="https://picsum.photos/seed/1939100567/1200/800"
      />
        </SectionErrorBoundary>
      </div>
  );
}
