// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "partnerships" section.

import React from 'react';
import PricingCenteredCards from '@/components/sections/pricing/PricingCenteredCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PartnershipsSection(): React.JSX.Element {
  return (
    <div id="partnerships" data-section="partnerships">
        <SectionErrorBoundary name="partnerships">
              <PricingCenteredCards
          tag="Partnership Options"
          title="Choose Your Growth Path"
          description="Selective partnerships for businesses focused on scaling."
          plans={[
            {
              tag: "Quarterly",
              price: "Quarterly Growth",
              description: "Full lead generation system, dedicated account manager, monthly optimization.",
              features: [
                "Full lead generation system",
                "Dedicated account manager",
                "Monthly optimization",
                "Priority support",
              ],
              primaryButton: {
                text: "Apply Now",
                href: "#apply",
              },
            },
            {
              tag: "Annual",
              price: "Annual Growth",
              description: "Highest service priority, strategic planning, and fastest response times.",
              features: [
                "Reduced effective monthly rate",
                "Strategic planning sessions",
                "Highest service priority",
                "Fastest response times",
                "Preferred client status",
              ],
              primaryButton: {
                text: "Apply Now",
                href: "#apply",
              },
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
