// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "process" section.

import React from 'react';
import FeaturesDetailedSteps from '@/components/sections/features/FeaturesDetailedSteps';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProcessSection(): React.JSX.Element {
  return (
    <div id="process" data-section="process">
        <SectionErrorBoundary name="process">
              <FeaturesDetailedSteps
          tag="Our Methodology"
          title="The Path to Predictable Growth"
          description="A refined, systematic approach to client acquisition."
          steps={[
            {
              tag: "01",
              title: "Identify",
              subtitle: "Market Intelligence",
              description: "We locate buyers actively interested in your service through custom intent mapping.",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendered-design-elements-assortment_23-2148996776.jpg",
            },
            {
              tag: "02",
              title: "Engage",
              subtitle: "Personalized Outreach",
              description: "Highly personalized sequences designed to start meaningful, authentic conversations.",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-woman-holding-tablet_23-2148993916.jpg",
            },
            {
              tag: "03",
              title: "Qualify",
              subtitle: "Rigorous Vetting",
              description: "Prospects are vetted against your criteria before a formal introduction is made.",
              imageSrc: "http://img.b2bpic.net/free-photo/graduation-high-school-university-concept-space-text_185193-110712.jpg",
            },
            {
              tag: "04",
              title: "Deliver",
              subtitle: "Direct Introduction",
              description: "Qualified opportunities are handed off directly to your team, ready to close.",
              imageSrc: "http://img.b2bpic.net/free-photo/delivery-still-life-with-toy-trucks_23-2148790053.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
