// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-us" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Target, TrendingUp, User } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WhyUsSection(): React.JSX.Element {
  return (
    <div id="why-us" data-section="why-us">
        <SectionErrorBoundary name="why-us">
              <AboutFeaturesSplit
          tag="Why GenGarden"
          title="Growth, Refined."
          description="We replace vanity metrics with tangible, revenue-generating conversations."
          items={[
            {
              icon: Target,
              title: "Qualified Opportunities",
              description: "Focused on outcomes, not clicks.",
            },
            {
              icon: TrendingUp,
              title: "Consistent Lead Flow",
              description: "Predictable results month over month.",
            },
            {
              icon: User,
              title: "Dedicated Support",
              description: "Account management that understands your brand.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/3d-rendering-modern-luxury-hotel-office-reception-meeting-lounge_105762-2045.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
